# Render үшін порт
server.port=${PORT:8080}

# МАҢЫЗДЫ: 'mem' орнына 'file' қолданамыз. 
# Бұл жобаның түбінде db_finance.mv.db деген файл құрады.
spring.datasource.url=jdbc:h2:file:./db_finance;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate баптаулары
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Groq API Key
groq.api.key=${GROQ_API_KEY}

# Базаның ішін браузерден көру үшін (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console